
import {
  Sun, Moon, Fingerprint, Eye, EyeOff, LogOut, Menu, User, Users, Home, BarChart2, FileText, Bell, BellOff,
  ChevronDown, ChevronLeft, ChevronRight, HardDrive, TestTube2, AlertCircle, RefreshCw, X, Check, Search, Plus, Trash2, Edit,
  Calendar, Lock, Download, Globe, List, Clock, Hexagon, ArrowLeft, LayoutDashboard, AlertTriangle, Shield, Send, Info, Settings
} from 'lucide-react';

export const Icons = {
  Sun,
  Moon,
  Fingerprint,
  Eye,
  EyeOff,
  LogOut,
  Menu,
  User,
  Users,
  Home,
  Desk: LayoutDashboard, // Used for "میز کار"
  BarChart: BarChart2,
  FileText,
  Bell,
  BellOff,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  HardDrive,
  TestTube: TestTube2,
  AlertCircle,
  Refresh: RefreshCw,
  X,
  Check,
  Search,
  Plus,
  Trash: Trash2,
  Trash2,
  Edit,
  Calendar,
  Lock,
  Download,
  Globe,
  List,
  Clock,
  Hexagon,
  ArrowLeft,
  AlertTriangle,
  Shield,
  Send,
  Info,
  Settings
};
